"""add wallet and wallet transactions

Revision ID: 382ef36cfd7b
Revises: a67845323715
Create Date: 2026-08-20 14:33:45.104301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '382ef36cfd7b'
down_revision: Union[str, None] = 'a67845323715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=0), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('wallet_transactions',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('deposit', 'purchase', 'refund', 'admin_credit', 'admin_debit', name='wallet_transaction_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=0), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=0), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    # NOTE: autogenerate wants to drop ix_products_{name,description}_trgm
    # here — false positive, same as in the previous migration (they're raw
    # SQL indexes, not represented in ORM metadata). Left in place.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_table('wallets')
    # ### end Alembic commands ###
